In [1]:
import tensorflow as tf

### Initailization of Tensors

In [2]:
x = tf.constant(4, shape=(1,1), dtype=tf.float32)
print(x)

tf.Tensor([[4.]], shape=(1, 1), dtype=float32)


In [3]:
y = tf.constant([[1,2,3],[4,5,6]])
print(y)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [4]:
ones = tf.ones((3,3))
print(ones)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)


In [5]:
zeros = tf.zeros((2,3))
print(zeros)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)


In [6]:
eye = tf.eye(3)
print(eye)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [7]:
rand_normal = tf.random.normal((3,3), mean=0, stddev=1)
print(rand_normal)

tf.Tensor(
[[ 1.402573    1.2839295   0.3071139 ]
 [-0.20097618  1.6386019  -0.8914685 ]
 [ 0.6259464  -0.04145314  0.64458066]], shape=(3, 3), dtype=float32)


In [8]:
rand_uniform = tf.random.uniform((1,3), minval=0, maxval=1)
print(rand_uniform)

tf.Tensor([[0.40725887 0.18703914 0.4342302 ]], shape=(1, 3), dtype=float32)


In [9]:
range_tf = tf.range(start = 1, limit = 10, delta = 2)
print(range_tf)

tf.Tensor([1 3 5 7 9], shape=(5,), dtype=int32)


In [10]:
new_range = tf.cast(range_tf, dtype=tf.float64)
#tf.float (16, 32, 64), tf.int (8, 16, 32, 64), tf.bool
print(new_range)

tf.Tensor([1. 3. 5. 7. 9.], shape=(5,), dtype=float64)


### Mathematical Operations

In [11]:
x = tf.constant([1,2,3])
y = tf.constant([9,8,7])

In [12]:
z = tf.add(x, y)
print(z)

z = x + y
print(z)

tf.Tensor([10 10 10], shape=(3,), dtype=int32)
tf.Tensor([10 10 10], shape=(3,), dtype=int32)


In [13]:
z = tf.subtract(x, y)
print(z)
z = x - y
print(z)

tf.Tensor([-8 -6 -4], shape=(3,), dtype=int32)
tf.Tensor([-8 -6 -4], shape=(3,), dtype=int32)


In [14]:
z = tf.divide(x, y)
print(z)
z = x / y
print(z)

tf.Tensor([0.11111111 0.25       0.42857143], shape=(3,), dtype=float64)
tf.Tensor([0.11111111 0.25       0.42857143], shape=(3,), dtype=float64)


In [15]:
z = tf.multiply(x, y)
print(z)
z = x * y
print(z)

tf.Tensor([ 9 16 21], shape=(3,), dtype=int32)
tf.Tensor([ 9 16 21], shape=(3,), dtype=int32)


In [16]:
z = tf.tensordot(x, y, axes = 1)
print(z)
z = tf.reduce_sum(x * y, axis = 0)
print(z)

tf.Tensor(46, shape=(), dtype=int32)
tf.Tensor(46, shape=(), dtype=int32)


In [17]:
z = x ** 5
print(z)

tf.Tensor([  1  32 243], shape=(3,), dtype=int32)


In [18]:
x = tf.random.normal((2, 3))
y = tf.random.normal((3, 4))
z = tf.matmul(x, y)
print(z)
z = x @ y
print(z)

tf.Tensor(
[[ 3.705955    2.685605   -0.27950686  1.7571474 ]
 [ 1.0321888   0.24564308  0.3377271  -0.8473892 ]], shape=(2, 4), dtype=float32)
tf.Tensor(
[[ 3.705955    2.685605   -0.27950686  1.7571474 ]
 [ 1.0321888   0.24564308  0.3377271  -0.8473892 ]], shape=(2, 4), dtype=float32)


### Indexing

In [19]:
x = tf.constant([0,1,1,2,3,5,8,13])
print(x[:])

tf.Tensor([ 0  1  1  2  3  5  8 13], shape=(8,), dtype=int32)


In [20]:
print(x[1:])

tf.Tensor([ 1  1  2  3  5  8 13], shape=(7,), dtype=int32)


In [21]:
print(x[1:3])

tf.Tensor([1 1], shape=(2,), dtype=int32)


In [22]:
print(x[::2])

tf.Tensor([0 1 3 8], shape=(4,), dtype=int32)


In [23]:
print(x[::-1])

tf.Tensor([13  8  5  3  2  1  1  0], shape=(8,), dtype=int32)


In [24]:
x

<tf.Tensor: shape=(8,), dtype=int32, numpy=array([ 0,  1,  1,  2,  3,  5,  8, 13])>

In [26]:
indices = tf.constant([0, 3])
x_ind = tf.gather(x, indices)
print(x_ind)

tf.Tensor([0 2], shape=(2,), dtype=int32)


In [27]:
x = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])
print(x[0,:])
print(x[0:2, :])

tf.Tensor([1 2], shape=(2,), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


### Reshaping

In [30]:
x = tf.range(9)
print(x)

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)


In [32]:
m = tf.reshape(x, (3,3))
print(m)

tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)


In [33]:
t = tf.transpose(x, perm=[1,0])
print(t)

tf.Tensor(
[[0 3 6]
 [1 4 7]
 [2 5 8]], shape=(3, 3), dtype=int32)
